name: HRMS Frontend CI/CD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: code format fixting
        run: pnpm run format:fix

      - name: Check code formatting
        run: pnpm run format:check

      - name: Run build
        run: pnpm run build

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Load NVM to ensure Node/NPM are in the PATH
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # Navigate to your project folder
            cd /var/www/html/index

            # Update code and rebuild
            git pull origin master
            pnpm install
            pnpm run build

            # Restart your app using PM2
            pm2 restart next-app || pm2 start pnpm --name "next-app" -- start
